dist: releases
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
      - -X "github.com/acorn-io/acorn/pkg/version.Tag=v{{ .Version }}"
    # The docker build don't actually use the binaries generated here, so just build something
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-amd64
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/acorn-io/acorn"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-arm64
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/acorn-io/acorn"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-arm32v7
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/acorn-io/acorn"
      - "--platform=linux/arm/v7"
docker_manifests:
  - use: docker
    name_template: ghcr.io/acorn-io/acorn:v{{ .Version }}
    image_templates:
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-amd64
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-arm64
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-arm32v7
  - use: docker
    name_template: ghcr.io/acorn-io/acorn:latest
    image_templates:
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-amd64
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-arm64
      - ghcr.io/acorn-io/acorn:v{{ .Version }}-arm32v7
docker_signs:
  - artifacts: all
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'
