kind: ServiceAccount
apiVersion: v1
metadata:
  name: acorn-system
  namespace: acorn-system

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: acorn-controller
  namespace: acorn-system
spec:
  selector:
    matchLabels:
      app: acorn-controller
  template:
    metadata:
      labels:
        app: acorn-controller
    spec:
      containers:
        - name: acorn-controller
          image: ghcr.io/acorn-io/acorn
          args:
            - controller
      serviceAccountName: acorn-system