on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        #- uses: actions/setup-go@v2
        #  with:
        #    stable: false
        #    go-version: 1.18rc1
      - run: curl -sfL https://go.dev/dl/go1.18rc1.linux-amd64.tar.gz | sudo tar xzf - -C /usr/local
      - run: echo /usr/local/go/bin >> $GITHUB_PATH
      - uses: debianmaster/actions-k3s@v1.0.5
        with:
          version: 'latest'
      - run: make test
