name: main-release

on:
  push:
    branches:
    - main

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v1.4.1"
      - name: Setup Cosign
        run: |
          echo "${COSIGN_KEY}" > "$GITHUB_WORKSPACE/cosign.key"
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Push Docker Images
        run: |
          VERSION=v$(cat releases/metadata.json | jq -r .version)
          IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "$VERSION")
          for i in ${IMAGES}; do
            docker push $i
          done
          docker manifest create ghcr.io/acorn-io/acorn:main ${IMAGES}
          docker manifest push ghcr.io/acorn-io/acorn:main
          docker manifest create ghcr.io/acorn-io/acorn:${VERSION} ${IMAGES}
          docker manifest push ghcr.io/acorn-io/acorn:${VERSION}
      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: releases
          path: releases/
