name: test
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: debianmaster/actions-k3s@v1.0.5
        with:
          version: 'latest'
      - run: make test
